name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Date
        id: get-date
        run: |
          value=date::$(/bin/date -u "+%Y%m%d")
          echo "date=${value}" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: /home/linuxbrew
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}
      # Homebrew
      - name: homebrew installation
        run:  if [ ! -d /home/linuxbrew ]; then bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" -y; fi
      - name: set PATH
        run: export PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH
      - name: homebrew update
        run:  brew update
      - name: homebrew outdated
        run: brew outdated
      - name: homebrew upgrade
        run: brew upgrade
      # run tests
      - run: ln -s $PWD $HOME/.bashrc.d
      - run: set -xe
      - run: source __init__.sh
