name: build
on: [ push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: /home/linuxbrew
          key: ${{ runner.os }}-brew
          restore-keys: |
            ${{ runner.os }}-brew
      # Homebrew
      - name: homebrew installation
        run:  if [ ! -d /home/linuxbrew ]; then bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" -y; fi
      - name: set PATH
        run: export PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH
      - name: homebrew update
        run:  brew update
      - name: homebrew outdated
        run: brew outdated
      - name: homebrew upgrade
        run: brew upgrade
      - run: ln -s $PWD $HOME/.bashrc.d
      - run: ls -ashl $HOME/.bashrc.d
      - run: set -x
      - run: source __init__.sh
      # pre-commit
      - name: pre-commit installation
        run: brew install pre-commit
      - name: run pre-commit
        run: pre-commit run --verbose --all-files
